---
#
# edX Configuration
#
# github:     http://gitlab.cse.iitb.ac.in/indiax/configuration
# wiki:       http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki
# code style: http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki/Ansible-Coding-Conventions
# license:    http://gitlab.cse.iitb.ac.in/indiax/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role demo
#

demo_app_dir: "{{ COMMON_APP_DIR }}/demo"
demo_code_dir: "{{ demo_app_dir }}/edx-demo-course"
demo_repo: "https://{{ COMMON_GIT_MIRROR }}/edx/edx-demo-course.git"
demo_course_id: 'edX/Open_DemoX/edx_demo_course'
demo_version: "master"
demo_test_users:
  - email: 'honor@example.com'
    mode: honor
    password: edx
  - email: 'audit@example.com'
    mode: audit
    password: edx
  - email: 'verified@example.com'
    mode: verified
    password: edx

demo_edxapp_user: 'edxapp'
demo_edxapp_venv_bin: '{{COMMON_APP_DIR}}/{{demo_edxapp_user}}/venvs/{{demo_edxapp_user}}/bin'
demo_edxapp_course_data_dir: '{{COMMON_DATA_DIR}}/{{demo_edxapp_user}}/data'
demo_edxapp_code_dir: '{{COMMON_APP_DIR}}/{{demo_edxapp_user}}/edx-platform'
